### ISSUE TITLE
Нужна помощь в установке модуля loveorigami/lo-module-eav

### ISSUE THREAD

**Issue by potter062** [loveorigami/lo-module-eav#1]
Устанавливаю, как написано в документации. Подскажите, пожалуйста, в какие файлы вносить изменения. Запутался, если можно, то напишите пути к файлам примерно в таком виде:

    root/backend/config/main.php

Я чайник, но многое настроил сам, а с этим модулем пока никак, очень надеюсь на понимание и поддержку.

**Comment by loveorigami** [comment]
Этот модуль не работает самостоятельно. Для его работы нужен модуль lo-core + специальный мета класс (разрабатывался для внутренней cms).
поэтому он называется lo-eav a не yii2-eav

рекомендую поискать именно yii2-eav
https://github.com/search?utf8=%E2%9C%93&q=yii2+eav&type=

например
https://github.com/yeesoft/yii2-yee-eav

**Comment by potter062** [comment]
Я извиняюсь за назойливость но я прочитал в yeesoft/yii2-yee-eav что вы устанавливали ихний модуль и я так понял что у вашего модуля много общего с yeesoft/yii2-yee-eav. Не могли бы вы помочь как правильно его установить никак не получается а вы как то его поставили. Если можно то на почту potter062@gmail.com Я просто запутался. 
В модели Post уже указано
class Post extends ActiveRecord implements OwnerAccess
А по инструкции надо добавить
class PostModel extends ActiveRecord implements yeesoft\eav\models\EavCategories
другими словами очень нуждаюсь в помощи
